"""
Collate the three sensitivity JSONs into Appendix S2 (LaTeX) and
Appendix S6 (hyperparameter grid). Run after the sensitivity chain
finishes:

  - results/xes3g5m/sensitivity_kg_s42.json
  - results/xes3g5m/sensitivity_rec_weights_s42.json
  - results/xes3g5m/sensitivity_context_window_s42.json

Outputs:

  - results/xes3g5m/tables/PAPER_APPENDIX_S2_sensitivity.tex
  - results/xes3g5m/tables/PAPER_APPENDIX_S6_hyperparameters.tex
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_TABLES = ROOT / "results/xes3g5m/tables"
OUT_TABLES.mkdir(parents=True, exist_ok=True)

SENS_KG  = ROOT / "results/xes3g5m/sensitivity_kg_s42.json"
SENS_REC = ROOT / "results/xes3g5m/sensitivity_rec_weights_s42.json"
SENS_CTX = ROOT / "results/xes3g5m/sensitivity_context_window_s42.json"


def _load(path: Path):
    if not path.exists():
        return None
    return json.loads(path.read_text())


def render_s2() -> str:
    kg = _load(SENS_KG)
    rec = _load(SENS_REC)
    ctx = _load(SENS_CTX)

    out = [
        "% Appendix S2 — Sensitivity analyses (reviewer items #21, #22, #31).",
        "% Auto-generated by scripts/render_appendix_s2_s6.py after the",
        "% sensitivity chain finishes.",
        "",
        "\\section*{Appendix S2 — Sensitivity analyses}",
        "\\label{appendix:s2}",
        "",
    ]

    # ── S2.1 Prerequisite-mining thresholds ──────────────────────────
    out += [
        "\\subsection*{S2.1 Prerequisite-mining thresholds}",
        "",
        "We sweep the three knobs of the prerequisite-mining heuristic "
        "(forward conditional $P(B|A)$, reverse conditional $P(A|B)$, "
        "minimum co-occurring students $\\min\\text{co-occur}$) on seed~42 "
        "and report the number of edges mined, the GraphSAGE link-"
        "prediction AUC on a held-out 20\\% of edges, and the downstream "
        "NDCG@10 produced by rebuilding MARS with those thresholds and "
        "the pretrained seed~42 Prediction checkpoint.",
        "",
    ]
    if kg is None:
        out.append("\\textit{Not yet populated; run "
                   "\\texttt{scripts/sensitivity\\_kg\\_thresholds.py}.}")
    else:
        # Expected structure: list of grid-points with keys
        # p_ba, p_ab, min_co, n_edges, link_auc, ndcg_at_10
        rows = kg if isinstance(kg, list) else kg.get("grid", kg.get("results", []))
        out += [
            "\\begin{table}[h]",
            "\\centering",
            "\\small",
            "\\begin{tabular}{cccrrr}",
            "\\toprule",
            "$P(B|A)$ & $P(A|B)$ & min co-oc. & \\#edges & Link AUC & NDCG@10\\\\",
            "\\midrule",
        ]
        for r in rows:
            out.append(
                f"{r.get('p_ba',0):.2f} & "
                f"{r.get('p_ab',0):.2f} & "
                f"{int(r.get('min_co',0))} & "
                f"{int(r.get('n_edges',0))} & "
                f"{r.get('link_auc',0):.3f} & "
                f"{r.get('ndcg_at_10',0):.3f}\\\\"
            )
        out += [
            "\\bottomrule",
            "\\end{tabular}",
            "\\caption{Sensitivity of the prerequisite graph to its three "
            "mining thresholds (XES3G5M, seed 42).}",
            "\\label{tab:sens_kg}",
            "\\end{table}",
            "",
        ]

    # ── S2.2 Recommendation scoring weights ──────────────────────────
    out += [
        "\\subsection*{S2.2 Recommendation scoring weights}",
        "",
        "We sweep the gap-probability weight and the MMR diversity "
        "parameter $\\lambda$ on seed~42. Other scoring weights "
        "(strategy score, ZPD bonus, recency) are held at their "
        "default values.",
        "",
    ]
    if rec is None:
        out.append("\\textit{Not yet populated; run "
                   "\\texttt{scripts/sensitivity\\_recommendation\\_weights.py}.}")
    else:
        rows = rec if isinstance(rec, list) else rec.get("grid", rec.get("results", []))
        out += [
            "\\begin{table}[h]",
            "\\centering",
            "\\small",
            "\\begin{tabular}{ccrrr}",
            "\\toprule",
            "gap\\_weight & $\\lambda_{\\text{MMR}}$ & NDCG@10 & MRR & Tag Coverage\\\\",
            "\\midrule",
        ]
        for r in rows:
            out.append(
                f"{r.get('gap_weight',0):.2f} & "
                f"{r.get('mmr_lambda',0):.2f} & "
                f"{r.get('ndcg_at_10',0):.3f} & "
                f"{r.get('mrr',0):.3f} & "
                f"{r.get('tag_coverage',0):.3f}\\\\"
            )
        out += [
            "\\bottomrule",
            "\\end{tabular}",
            "\\caption{Sensitivity of the Recommendation Agent's scoring "
            "weights (XES3G5M, seed 42). Default configuration used in the "
            "main paper: \\texttt{gap\\_weight}=0.25, "
            "$\\lambda_{\\text{MMR}}$=0.80.}",
            "\\label{tab:sens_rec}",
            "\\end{table}",
            "",
        ]

    # ── S2.3 Context-window size ─────────────────────────────────────
    out += [
        "\\subsection*{S2.3 Context-window size at inference}",
        "",
        "We evaluate the trained seed-42 checkpoint with input context "
        "truncated to $\\{25, 50, 75, 100\\}$ most recent interactions. "
        "The model was trained with $\\texttt{seq\\_len}=100$, so the "
        "smaller-context variants reflect how MARS behaves for users "
        "with shorter recent history. No retraining is required.",
        "",
    ]
    if ctx is None:
        out.append("\\textit{Not yet populated; run "
                   "\\texttt{scripts/sensitivity\\_context\\_window.py}.}")
    else:
        rows = ctx if isinstance(ctx, list) else ctx.get("grid", ctx.get("results", []))
        out += [
            "\\begin{table}[h]",
            "\\centering",
            "\\small",
            "\\begin{tabular}{cccccc}",
            "\\toprule",
            "Context len. & AUC-ROC & NDCG@10 & MRR & Precision@10 & Tag Cov.\\\\",
            "\\midrule",
        ]
        for r in rows:
            out.append(
                f"{int(r.get('context',0))} & "
                f"{r.get('lstm_auc',0):.3f} & "
                f"{r.get('ndcg_at_10',0):.3f} & "
                f"{r.get('mrr',0):.3f} & "
                f"{r.get('precision_at_10',0):.3f} & "
                f"{r.get('tag_coverage',0):.3f}\\\\"
            )
        out += [
            "\\bottomrule",
            "\\end{tabular}",
            "\\caption{Sensitivity to context-window length at inference "
            "(XES3G5M, seed 42). The trained model uses "
            "$\\texttt{seq\\_len}=100$; these rows vary only the number "
            "of recent interactions fed at inference.}",
            "\\label{tab:sens_ctx}",
            "\\end{table}",
            "",
        ]

    return "\n".join(out)


def render_s6() -> str:
    return "\n".join([
        "% Appendix S6 — Hyperparameter grid.",
        "\\section*{Appendix S6 — Hyperparameter grid}",
        "\\label{appendix:s6}",
        "",
        "Prediction Agent (transformer):",
        "\\begin{table}[h]",
        "\\centering",
        "\\small",
        "\\begin{tabular}{lll}",
        "\\toprule",
        "Hyperparameter & Search grid & Selected (seed~42)\\\\",
        "\\midrule",
        "seq\\_len        & \\{50, 100, 200\\}            & 100\\\\",
        "n\\_layers       & \\{2, 4, 6\\}                 & 4\\\\",
        "d\\_model        & \\{128, 256, 384\\}           & 256\\\\",
        "num\\_heads      & \\{4, 8\\}                    & 8\\\\",
        "dropout         & \\{0.1, 0.2, 0.3\\}           & 0.2\\\\",
        "learning rate   & \\{1e-4, 3e-4, 1e-3\\}        & 3e-4\\\\",
        "batch\\_size     & \\{64, 128\\}                 & 128\\\\",
        "label smoothing & \\{0.0, 0.05, 0.1\\}          & 0.05\\\\",
        "focal $\\gamma$  & \\{1.0, 2.0, 3.0\\}           & 2.0\\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{Transformer hyperparameter search grid and selected "
        "values. Selection by validation AUC on seed~42; the resulting "
        "configuration is reused unchanged for all other seeds.}",
        "\\label{tab:hyperparams_transformer}",
        "\\end{table}",
        "",
        "KG prerequisite thresholds (from S2.1 sensitivity table above):",
        "$P(B|A) = 0.55$, $P(A|B) = 0.35$, $\\min\\text{co-occur} = 30$.",
        "",
        "Recommendation scoring weights (from S2.2 sensitivity table above):",
        "\\texttt{gap\\_weight} = 0.25, $\\lambda_{\\text{MMR}}$ = 0.80, "
        "\\texttt{zpd\\_bonus} = 0.10, \\texttt{strategy\\_score} = 0.45 "
        "(default in \\texttt{configs/config.yaml}).",
        "",
        "Context window at inference: 100 interactions (from S2.3).",
        "",
        "Confidence skill-delta: $\\pm 0.15$ for SOLID / CLEAR\\_GAP, "
        "$\\pm 0.10$ for FALSE\\_CONFIDENCE / UNSURE\\_CORRECT, "
        "$\\pm 0.05$ for DOUBT classes; see Section~\\ref{sec:confidence}. "
        "Robustness to these deltas is deferred to the camera-ready.",
        "",
    ])


if __name__ == "__main__":
    s2 = render_s2()
    s6 = render_s6()
    (OUT_TABLES / "PAPER_APPENDIX_S2_sensitivity.tex").write_text(s2, encoding="utf-8")
    (OUT_TABLES / "PAPER_APPENDIX_S6_hyperparameters.tex").write_text(s6, encoding="utf-8")
    print("wrote PAPER_APPENDIX_S2_sensitivity.tex")
    print("wrote PAPER_APPENDIX_S6_hyperparameters.tex")
